import {
    SukuBidTagComponent,
    SukuCardLineComponent,
    SukuCheckboxComponent,
    SukuDashboardProfileComponent,
    SukuDefaultButtonComponent,
    SukuFiltersComponent,
    SukuHeadingComponent,
    SukuHomeHeadingComponent,
    SukuHomeItalicHeadingComponent,
    SukuHomeWidgetComponent,
    SukuInfoButtonComponent,
    SukuInlineDropDownComponent,
    SukuMailWidgetComponent,
    SukuMatchChipComponent,
    SukuNotificationBoxComponent,
    SukuPrimaryButtonComponent,
    SukuProgressBarComponent,
    SukuRadioButtonComponent,
    SukuSecondaryButtonComponent,
    SukuSubHeadingComponent,
    SukuRatingComponent,
    SukuRatingLineItemComponent,
    SukuLinkComponent,
    SukuAddWidgetComponent,
    SukuSelectInputComponent,
    SukuNavSubmenuComponent,
    SukuBidInfoComponent,
    SukuPhoneWidgetComponent,
    SukuAddressWidgetComponent,
    SukuSearchInputComponent,
    SukuProfileWidgetComponent,
    SukuStarBadgeComponent,
    SukuCardTitleComponent,
    SukuCardListComponent,
    SukuHeadingNestComponent,
    SukuSubNestHeadingComponent,
    SukuInputComponent,
    SukuResponseComponent,
    SukuTreeComponent,
    DynamicFormComponent,
    SukuTrackProgressBarComponent,
    SukuTrackTraceProductSearchComponent
} from './webcomponent';
import { SukuACHSettingsComponent } from './suku-achsettings/suku-achsettings.component';
import { SukuTransactionHistoryComponent } from './suku-transaction-history/suku-transaction-history.component';
import { SukuBeneficialOwnerComponent } from './suku-beneficial-owner/suku-beneficial-owner.component';
import { SukuDwollaFundingAgreementComponent } from './suku-dwolla-funding-agreement/suku-dwolla-funding-agreement.component';
import { SukuDwollaFundingSourceComponent } from './suku-dwolla-funding-source/suku-dwolla-funding-source.component';

export const WebComponents = [
    SukuHeadingComponent,
    SukuSubHeadingComponent,
    SukuDashboardProfileComponent,
    SukuNotificationBoxComponent,
    SukuHomeHeadingComponent,
    SukuHomeWidgetComponent,
    SukuFiltersComponent,
    SukuHomeItalicHeadingComponent,
    SukuInfoButtonComponent,
    SukuPrimaryButtonComponent,
    SukuDefaultButtonComponent,
    SukuProgressBarComponent,
    SukuMailWidgetComponent,
    SukuPhoneWidgetComponent,
    SukuAddressWidgetComponent,
    SukuInlineDropDownComponent,
    SukuCheckboxComponent,
    SukuRadioButtonComponent,
    SukuCardLineComponent,
    SukuSecondaryButtonComponent,
    SukuBidTagComponent,
    SukuMatchChipComponent,
    SukuRatingComponent,
    SukuRatingLineItemComponent,
    SukuLinkComponent,
    SukuAddWidgetComponent,
    SukuSelectInputComponent,
    SukuNavSubmenuComponent,
    SukuBidInfoComponent,
    SukuSearchInputComponent,
    SukuProfileWidgetComponent,
    SukuStarBadgeComponent,
    SukuHeadingNestComponent,
    SukuCardTitleComponent,
    SukuCardListComponent,
    SukuSubNestHeadingComponent,
    SukuInputComponent,
    SukuResponseComponent,
    SukuTreeComponent,
    DynamicFormComponent,
    SukuTrackProgressBarComponent,
    SukuTrackTraceProductSearchComponent,
    SukuACHSettingsComponent,
    SukuTransactionHistoryComponent,
    SukuDwollaFundingAgreementComponent,
    SukuBeneficialOwnerComponent,
    SukuDwollaFundingSourceComponent
];


