import {
	SukuCardLineComponent,
	SukuCheckboxComponent,
	SukuDashboardProfileComponent,
	SukuDefaultButtonComponent,
	SukuFiltersComponent,
	SukuHeadingComponent,
	SukuHomeHeadingComponent,
	SukuHomeItalicHeadingComponent,
	SukuHomeWidgetComponent,
	SukuInfoButtonComponent,
	SukuInlineDropDownComponent,
	SukuMailWidgetComponent,
	SukuMatchChipComponent,
	SukuNotificationBoxComponent,
	SukuPrimaryButtonComponent,
	SukuProgressBarComponent,
	SukuRadioButtonComponent,
	SukuSecondaryButtonComponent,
	SukuSubHeadingComponent,
	SukuRatingComponent,
	SukuRatingLineItemComponent,
	SukuLinkComponent,
	SukuAddWidgetComponent,
	SukuSelectInputComponent,
	SukuNavSubmenuComponent,
	SukuBidInfoComponent,
	SukuPhoneWidgetComponent,
	SukuAddressWidgetComponent,
	SukuSearchInputComponent,
	SukuProfileWidgetComponent,
	SukuStarBadgeComponent,
	SukuCardTitleComponent,
	SukuCardListComponent,
	SukuHeadingNestComponent,
	SukuSubNestHeadingComponent,
	SukuInputComponent,
	SukuResponseComponent,
	SukuTreeComponent,
	DynamicFormComponent,
	SukuTrackProgressBarComponent,
	SukuTrackTraceProductSearchComponent
} from './webcomponent';
import { SukuACHSettingsComponent } from './suku-achsettings/suku-achsettings.component';
import { SukuTransactionHistoryComponent } from './suku-transaction-history/suku-transaction-history.component';
import { SukuBeneficialOwnerComponent } from './suku-beneficial-owner/suku-beneficial-owner.component';
import { SukuDwollaFundingAgreementComponent } from './suku-dwolla-funding-agreement/suku-dwolla-funding-agreement.component';
import { SukuDwollaFundingSourceComponent } from './suku-dwolla-funding-source/suku-dwolla-funding-source.component';
import { SukuTextEditorComponent } from './suku-text-editor/suku-text-editor.component';
import { SukuProposalHeaderComponent } from './suku-proposal-header/suku-proposal-header.component';
import { SukuOptionModalComponent } from './suku-proposal-option-modal/suku-option-modal.component';
import { suku } from './suku-governance-webcomponents.service';
import { SukuDoughnutChartWidgetComponent } from './suku-doughnut-chart-widget/suku-doughnut-chart-widget.component';
import { SukuGovernanceFilterComponent } from './suku-governance-filter/suku-governance-filter.component';
import { SukuProposalOptionModalComponent } from './suku-proposal-option-modal/suku-proposal-option-modal.component';
import { SukuListProposalChoiceWidgetComponent } from './suku-list-proposal-choice-widget/suku-list-proposal-choice-widget.component';

export const WebComponents = [
	SukuHeadingComponent,
	SukuSubHeadingComponent,
	SukuDashboardProfileComponent,
	SukuNotificationBoxComponent,
	SukuHomeHeadingComponent,
	SukuHomeWidgetComponent,
	SukuFiltersComponent,
	SukuHomeItalicHeadingComponent,
	SukuInfoButtonComponent,
	SukuPrimaryButtonComponent,
	SukuDefaultButtonComponent,
	SukuProgressBarComponent,
	SukuMailWidgetComponent,
	SukuPhoneWidgetComponent,
	SukuAddressWidgetComponent,
	SukuInlineDropDownComponent,
	SukuCheckboxComponent,
	SukuRadioButtonComponent,
	SukuCardLineComponent,
	SukuSecondaryButtonComponent,
	SukuMatchChipComponent,
	SukuRatingComponent,
	SukuRatingLineItemComponent,
	SukuLinkComponent,
	SukuAddWidgetComponent,
	SukuSelectInputComponent,
	SukuNavSubmenuComponent,
	SukuBidInfoComponent,
	SukuSearchInputComponent,
	SukuProfileWidgetComponent,
	SukuStarBadgeComponent,
	SukuHeadingNestComponent,
	SukuCardTitleComponent,
	SukuCardListComponent,
	SukuSubNestHeadingComponent,
	SukuInputComponent,
	SukuResponseComponent,
	SukuTreeComponent,
	DynamicFormComponent,
	SukuTrackProgressBarComponent,
	SukuTrackTraceProductSearchComponent,
	SukuACHSettingsComponent,
	SukuTransactionHistoryComponent,
	SukuDwollaFundingAgreementComponent,
	SukuBeneficialOwnerComponent,
	SukuDwollaFundingSourceComponent,
	SukuTextEditorComponent,
	SukuProposalHeaderComponent,
	SukuOptionModalComponent,
	SukuProposalOptionModalComponent,
	SukuDoughnutChartWidgetComponent,
	SukuListProposalChoiceWidgetComponent,
	SukuGovernanceFilterComponent
];
